[build]
  # Netlifyで公開するディレクトリを指定
  publish = "public"

# リダイレクト設定（SPAでない場合は通常不要だが、将来的な拡張のために記載）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  force = false

# ヘッダー設定（セキュリティとパフォーマンス向上）
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静的ファイルのキャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTMLファイルのキャッシュ設定
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 圧縮設定（Netlifyが自動で行うが、明示的に設定）
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"